# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/vowpal_wabbit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/vowpal_wabbit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/vowpal_wabbit/CMakeFiles /opt/vowpal_wabbit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/vowpal_wabbit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vw

# Build rule for target.
vw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vw
.PHONY : vw

# fast build rule for target.
vw/fast:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/build
.PHONY : vw/fast

#=============================================================================
# Target rules for targets named vwexe

# Build rule for target.
vwexe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vwexe
.PHONY : vwexe

# fast build rule for target.
vwexe/fast:
	$(MAKE) -f CMakeFiles/vwexe.dir/build.make CMakeFiles/vwexe.dir/build
.PHONY : vwexe/fast

vowpalwabbit/accumulate.o: vowpalwabbit/accumulate.cc.o
.PHONY : vowpalwabbit/accumulate.o

# target to build an object file
vowpalwabbit/accumulate.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/accumulate.cc.o
.PHONY : vowpalwabbit/accumulate.cc.o

vowpalwabbit/accumulate.i: vowpalwabbit/accumulate.cc.i
.PHONY : vowpalwabbit/accumulate.i

# target to preprocess a source file
vowpalwabbit/accumulate.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/accumulate.cc.i
.PHONY : vowpalwabbit/accumulate.cc.i

vowpalwabbit/accumulate.s: vowpalwabbit/accumulate.cc.s
.PHONY : vowpalwabbit/accumulate.s

# target to generate assembly for a file
vowpalwabbit/accumulate.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/accumulate.cc.s
.PHONY : vowpalwabbit/accumulate.cc.s

vowpalwabbit/active.o: vowpalwabbit/active.cc.o
.PHONY : vowpalwabbit/active.o

# target to build an object file
vowpalwabbit/active.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active.cc.o
.PHONY : vowpalwabbit/active.cc.o

vowpalwabbit/active.i: vowpalwabbit/active.cc.i
.PHONY : vowpalwabbit/active.i

# target to preprocess a source file
vowpalwabbit/active.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active.cc.i
.PHONY : vowpalwabbit/active.cc.i

vowpalwabbit/active.s: vowpalwabbit/active.cc.s
.PHONY : vowpalwabbit/active.s

# target to generate assembly for a file
vowpalwabbit/active.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active.cc.s
.PHONY : vowpalwabbit/active.cc.s

vowpalwabbit/active_cover.o: vowpalwabbit/active_cover.cc.o
.PHONY : vowpalwabbit/active_cover.o

# target to build an object file
vowpalwabbit/active_cover.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active_cover.cc.o
.PHONY : vowpalwabbit/active_cover.cc.o

vowpalwabbit/active_cover.i: vowpalwabbit/active_cover.cc.i
.PHONY : vowpalwabbit/active_cover.i

# target to preprocess a source file
vowpalwabbit/active_cover.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active_cover.cc.i
.PHONY : vowpalwabbit/active_cover.cc.i

vowpalwabbit/active_cover.s: vowpalwabbit/active_cover.cc.s
.PHONY : vowpalwabbit/active_cover.s

# target to generate assembly for a file
vowpalwabbit/active_cover.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/active_cover.cc.s
.PHONY : vowpalwabbit/active_cover.cc.s

vowpalwabbit/allreduce_sockets.o: vowpalwabbit/allreduce_sockets.cc.o
.PHONY : vowpalwabbit/allreduce_sockets.o

# target to build an object file
vowpalwabbit/allreduce_sockets.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_sockets.cc.o
.PHONY : vowpalwabbit/allreduce_sockets.cc.o

vowpalwabbit/allreduce_sockets.i: vowpalwabbit/allreduce_sockets.cc.i
.PHONY : vowpalwabbit/allreduce_sockets.i

# target to preprocess a source file
vowpalwabbit/allreduce_sockets.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_sockets.cc.i
.PHONY : vowpalwabbit/allreduce_sockets.cc.i

vowpalwabbit/allreduce_sockets.s: vowpalwabbit/allreduce_sockets.cc.s
.PHONY : vowpalwabbit/allreduce_sockets.s

# target to generate assembly for a file
vowpalwabbit/allreduce_sockets.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_sockets.cc.s
.PHONY : vowpalwabbit/allreduce_sockets.cc.s

vowpalwabbit/allreduce_threads.o: vowpalwabbit/allreduce_threads.cc.o
.PHONY : vowpalwabbit/allreduce_threads.o

# target to build an object file
vowpalwabbit/allreduce_threads.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_threads.cc.o
.PHONY : vowpalwabbit/allreduce_threads.cc.o

vowpalwabbit/allreduce_threads.i: vowpalwabbit/allreduce_threads.cc.i
.PHONY : vowpalwabbit/allreduce_threads.i

# target to preprocess a source file
vowpalwabbit/allreduce_threads.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_threads.cc.i
.PHONY : vowpalwabbit/allreduce_threads.cc.i

vowpalwabbit/allreduce_threads.s: vowpalwabbit/allreduce_threads.cc.s
.PHONY : vowpalwabbit/allreduce_threads.s

# target to generate assembly for a file
vowpalwabbit/allreduce_threads.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/allreduce_threads.cc.s
.PHONY : vowpalwabbit/allreduce_threads.cc.s

vowpalwabbit/autolink.o: vowpalwabbit/autolink.cc.o
.PHONY : vowpalwabbit/autolink.o

# target to build an object file
vowpalwabbit/autolink.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/autolink.cc.o
.PHONY : vowpalwabbit/autolink.cc.o

vowpalwabbit/autolink.i: vowpalwabbit/autolink.cc.i
.PHONY : vowpalwabbit/autolink.i

# target to preprocess a source file
vowpalwabbit/autolink.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/autolink.cc.i
.PHONY : vowpalwabbit/autolink.cc.i

vowpalwabbit/autolink.s: vowpalwabbit/autolink.cc.s
.PHONY : vowpalwabbit/autolink.s

# target to generate assembly for a file
vowpalwabbit/autolink.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/autolink.cc.s
.PHONY : vowpalwabbit/autolink.cc.s

vowpalwabbit/best_constant.o: vowpalwabbit/best_constant.cc.o
.PHONY : vowpalwabbit/best_constant.o

# target to build an object file
vowpalwabbit/best_constant.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/best_constant.cc.o
.PHONY : vowpalwabbit/best_constant.cc.o

vowpalwabbit/best_constant.i: vowpalwabbit/best_constant.cc.i
.PHONY : vowpalwabbit/best_constant.i

# target to preprocess a source file
vowpalwabbit/best_constant.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/best_constant.cc.i
.PHONY : vowpalwabbit/best_constant.cc.i

vowpalwabbit/best_constant.s: vowpalwabbit/best_constant.cc.s
.PHONY : vowpalwabbit/best_constant.s

# target to generate assembly for a file
vowpalwabbit/best_constant.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/best_constant.cc.s
.PHONY : vowpalwabbit/best_constant.cc.s

vowpalwabbit/bfgs.o: vowpalwabbit/bfgs.cc.o
.PHONY : vowpalwabbit/bfgs.o

# target to build an object file
vowpalwabbit/bfgs.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bfgs.cc.o
.PHONY : vowpalwabbit/bfgs.cc.o

vowpalwabbit/bfgs.i: vowpalwabbit/bfgs.cc.i
.PHONY : vowpalwabbit/bfgs.i

# target to preprocess a source file
vowpalwabbit/bfgs.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bfgs.cc.i
.PHONY : vowpalwabbit/bfgs.cc.i

vowpalwabbit/bfgs.s: vowpalwabbit/bfgs.cc.s
.PHONY : vowpalwabbit/bfgs.s

# target to generate assembly for a file
vowpalwabbit/bfgs.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bfgs.cc.s
.PHONY : vowpalwabbit/bfgs.cc.s

vowpalwabbit/binary.o: vowpalwabbit/binary.cc.o
.PHONY : vowpalwabbit/binary.o

# target to build an object file
vowpalwabbit/binary.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/binary.cc.o
.PHONY : vowpalwabbit/binary.cc.o

vowpalwabbit/binary.i: vowpalwabbit/binary.cc.i
.PHONY : vowpalwabbit/binary.i

# target to preprocess a source file
vowpalwabbit/binary.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/binary.cc.i
.PHONY : vowpalwabbit/binary.cc.i

vowpalwabbit/binary.s: vowpalwabbit/binary.cc.s
.PHONY : vowpalwabbit/binary.s

# target to generate assembly for a file
vowpalwabbit/binary.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/binary.cc.s
.PHONY : vowpalwabbit/binary.cc.s

vowpalwabbit/boosting.o: vowpalwabbit/boosting.cc.o
.PHONY : vowpalwabbit/boosting.o

# target to build an object file
vowpalwabbit/boosting.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/boosting.cc.o
.PHONY : vowpalwabbit/boosting.cc.o

vowpalwabbit/boosting.i: vowpalwabbit/boosting.cc.i
.PHONY : vowpalwabbit/boosting.i

# target to preprocess a source file
vowpalwabbit/boosting.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/boosting.cc.i
.PHONY : vowpalwabbit/boosting.cc.i

vowpalwabbit/boosting.s: vowpalwabbit/boosting.cc.s
.PHONY : vowpalwabbit/boosting.s

# target to generate assembly for a file
vowpalwabbit/boosting.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/boosting.cc.s
.PHONY : vowpalwabbit/boosting.cc.s

vowpalwabbit/bs.o: vowpalwabbit/bs.cc.o
.PHONY : vowpalwabbit/bs.o

# target to build an object file
vowpalwabbit/bs.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bs.cc.o
.PHONY : vowpalwabbit/bs.cc.o

vowpalwabbit/bs.i: vowpalwabbit/bs.cc.i
.PHONY : vowpalwabbit/bs.i

# target to preprocess a source file
vowpalwabbit/bs.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bs.cc.i
.PHONY : vowpalwabbit/bs.cc.i

vowpalwabbit/bs.s: vowpalwabbit/bs.cc.s
.PHONY : vowpalwabbit/bs.s

# target to generate assembly for a file
vowpalwabbit/bs.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/bs.cc.s
.PHONY : vowpalwabbit/bs.cc.s

vowpalwabbit/cache.o: vowpalwabbit/cache.cc.o
.PHONY : vowpalwabbit/cache.o

# target to build an object file
vowpalwabbit/cache.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cache.cc.o
.PHONY : vowpalwabbit/cache.cc.o

vowpalwabbit/cache.i: vowpalwabbit/cache.cc.i
.PHONY : vowpalwabbit/cache.i

# target to preprocess a source file
vowpalwabbit/cache.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cache.cc.i
.PHONY : vowpalwabbit/cache.cc.i

vowpalwabbit/cache.s: vowpalwabbit/cache.cc.s
.PHONY : vowpalwabbit/cache.s

# target to generate assembly for a file
vowpalwabbit/cache.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cache.cc.s
.PHONY : vowpalwabbit/cache.cc.s

vowpalwabbit/cb.o: vowpalwabbit/cb.cc.o
.PHONY : vowpalwabbit/cb.o

# target to build an object file
vowpalwabbit/cb.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb.cc.o
.PHONY : vowpalwabbit/cb.cc.o

vowpalwabbit/cb.i: vowpalwabbit/cb.cc.i
.PHONY : vowpalwabbit/cb.i

# target to preprocess a source file
vowpalwabbit/cb.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb.cc.i
.PHONY : vowpalwabbit/cb.cc.i

vowpalwabbit/cb.s: vowpalwabbit/cb.cc.s
.PHONY : vowpalwabbit/cb.s

# target to generate assembly for a file
vowpalwabbit/cb.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb.cc.s
.PHONY : vowpalwabbit/cb.cc.s

vowpalwabbit/cb_adf.o: vowpalwabbit/cb_adf.cc.o
.PHONY : vowpalwabbit/cb_adf.o

# target to build an object file
vowpalwabbit/cb_adf.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_adf.cc.o
.PHONY : vowpalwabbit/cb_adf.cc.o

vowpalwabbit/cb_adf.i: vowpalwabbit/cb_adf.cc.i
.PHONY : vowpalwabbit/cb_adf.i

# target to preprocess a source file
vowpalwabbit/cb_adf.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_adf.cc.i
.PHONY : vowpalwabbit/cb_adf.cc.i

vowpalwabbit/cb_adf.s: vowpalwabbit/cb_adf.cc.s
.PHONY : vowpalwabbit/cb_adf.s

# target to generate assembly for a file
vowpalwabbit/cb_adf.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_adf.cc.s
.PHONY : vowpalwabbit/cb_adf.cc.s

vowpalwabbit/cb_algs.o: vowpalwabbit/cb_algs.cc.o
.PHONY : vowpalwabbit/cb_algs.o

# target to build an object file
vowpalwabbit/cb_algs.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_algs.cc.o
.PHONY : vowpalwabbit/cb_algs.cc.o

vowpalwabbit/cb_algs.i: vowpalwabbit/cb_algs.cc.i
.PHONY : vowpalwabbit/cb_algs.i

# target to preprocess a source file
vowpalwabbit/cb_algs.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_algs.cc.i
.PHONY : vowpalwabbit/cb_algs.cc.i

vowpalwabbit/cb_algs.s: vowpalwabbit/cb_algs.cc.s
.PHONY : vowpalwabbit/cb_algs.s

# target to generate assembly for a file
vowpalwabbit/cb_algs.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cb_algs.cc.s
.PHONY : vowpalwabbit/cb_algs.cc.s

vowpalwabbit/cbify.o: vowpalwabbit/cbify.cc.o
.PHONY : vowpalwabbit/cbify.o

# target to build an object file
vowpalwabbit/cbify.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cbify.cc.o
.PHONY : vowpalwabbit/cbify.cc.o

vowpalwabbit/cbify.i: vowpalwabbit/cbify.cc.i
.PHONY : vowpalwabbit/cbify.i

# target to preprocess a source file
vowpalwabbit/cbify.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cbify.cc.i
.PHONY : vowpalwabbit/cbify.cc.i

vowpalwabbit/cbify.s: vowpalwabbit/cbify.cc.s
.PHONY : vowpalwabbit/cbify.s

# target to generate assembly for a file
vowpalwabbit/cbify.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cbify.cc.s
.PHONY : vowpalwabbit/cbify.cc.s

vowpalwabbit/comp_io.o: vowpalwabbit/comp_io.cc.o
.PHONY : vowpalwabbit/comp_io.o

# target to build an object file
vowpalwabbit/comp_io.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/comp_io.cc.o
.PHONY : vowpalwabbit/comp_io.cc.o

vowpalwabbit/comp_io.i: vowpalwabbit/comp_io.cc.i
.PHONY : vowpalwabbit/comp_io.i

# target to preprocess a source file
vowpalwabbit/comp_io.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/comp_io.cc.i
.PHONY : vowpalwabbit/comp_io.cc.i

vowpalwabbit/comp_io.s: vowpalwabbit/comp_io.cc.s
.PHONY : vowpalwabbit/comp_io.s

# target to generate assembly for a file
vowpalwabbit/comp_io.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/comp_io.cc.s
.PHONY : vowpalwabbit/comp_io.cc.s

vowpalwabbit/cost_sensitive.o: vowpalwabbit/cost_sensitive.cc.o
.PHONY : vowpalwabbit/cost_sensitive.o

# target to build an object file
vowpalwabbit/cost_sensitive.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cost_sensitive.cc.o
.PHONY : vowpalwabbit/cost_sensitive.cc.o

vowpalwabbit/cost_sensitive.i: vowpalwabbit/cost_sensitive.cc.i
.PHONY : vowpalwabbit/cost_sensitive.i

# target to preprocess a source file
vowpalwabbit/cost_sensitive.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cost_sensitive.cc.i
.PHONY : vowpalwabbit/cost_sensitive.cc.i

vowpalwabbit/cost_sensitive.s: vowpalwabbit/cost_sensitive.cc.s
.PHONY : vowpalwabbit/cost_sensitive.s

# target to generate assembly for a file
vowpalwabbit/cost_sensitive.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/cost_sensitive.cc.s
.PHONY : vowpalwabbit/cost_sensitive.cc.s

vowpalwabbit/csoaa.o: vowpalwabbit/csoaa.cc.o
.PHONY : vowpalwabbit/csoaa.o

# target to build an object file
vowpalwabbit/csoaa.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/csoaa.cc.o
.PHONY : vowpalwabbit/csoaa.cc.o

vowpalwabbit/csoaa.i: vowpalwabbit/csoaa.cc.i
.PHONY : vowpalwabbit/csoaa.i

# target to preprocess a source file
vowpalwabbit/csoaa.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/csoaa.cc.i
.PHONY : vowpalwabbit/csoaa.cc.i

vowpalwabbit/csoaa.s: vowpalwabbit/csoaa.cc.s
.PHONY : vowpalwabbit/csoaa.s

# target to generate assembly for a file
vowpalwabbit/csoaa.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/csoaa.cc.s
.PHONY : vowpalwabbit/csoaa.cc.s

vowpalwabbit/ect.o: vowpalwabbit/ect.cc.o
.PHONY : vowpalwabbit/ect.o

# target to build an object file
vowpalwabbit/ect.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ect.cc.o
.PHONY : vowpalwabbit/ect.cc.o

vowpalwabbit/ect.i: vowpalwabbit/ect.cc.i
.PHONY : vowpalwabbit/ect.i

# target to preprocess a source file
vowpalwabbit/ect.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ect.cc.i
.PHONY : vowpalwabbit/ect.cc.i

vowpalwabbit/ect.s: vowpalwabbit/ect.cc.s
.PHONY : vowpalwabbit/ect.s

# target to generate assembly for a file
vowpalwabbit/ect.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ect.cc.s
.PHONY : vowpalwabbit/ect.cc.s

vowpalwabbit/example.o: vowpalwabbit/example.cc.o
.PHONY : vowpalwabbit/example.o

# target to build an object file
vowpalwabbit/example.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/example.cc.o
.PHONY : vowpalwabbit/example.cc.o

vowpalwabbit/example.i: vowpalwabbit/example.cc.i
.PHONY : vowpalwabbit/example.i

# target to preprocess a source file
vowpalwabbit/example.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/example.cc.i
.PHONY : vowpalwabbit/example.cc.i

vowpalwabbit/example.s: vowpalwabbit/example.cc.s
.PHONY : vowpalwabbit/example.s

# target to generate assembly for a file
vowpalwabbit/example.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/example.cc.s
.PHONY : vowpalwabbit/example.cc.s

vowpalwabbit/ftrl.o: vowpalwabbit/ftrl.cc.o
.PHONY : vowpalwabbit/ftrl.o

# target to build an object file
vowpalwabbit/ftrl.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ftrl.cc.o
.PHONY : vowpalwabbit/ftrl.cc.o

vowpalwabbit/ftrl.i: vowpalwabbit/ftrl.cc.i
.PHONY : vowpalwabbit/ftrl.i

# target to preprocess a source file
vowpalwabbit/ftrl.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ftrl.cc.i
.PHONY : vowpalwabbit/ftrl.cc.i

vowpalwabbit/ftrl.s: vowpalwabbit/ftrl.cc.s
.PHONY : vowpalwabbit/ftrl.s

# target to generate assembly for a file
vowpalwabbit/ftrl.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/ftrl.cc.s
.PHONY : vowpalwabbit/ftrl.cc.s

vowpalwabbit/gd.o: vowpalwabbit/gd.cc.o
.PHONY : vowpalwabbit/gd.o

# target to build an object file
vowpalwabbit/gd.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd.cc.o
.PHONY : vowpalwabbit/gd.cc.o

vowpalwabbit/gd.i: vowpalwabbit/gd.cc.i
.PHONY : vowpalwabbit/gd.i

# target to preprocess a source file
vowpalwabbit/gd.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd.cc.i
.PHONY : vowpalwabbit/gd.cc.i

vowpalwabbit/gd.s: vowpalwabbit/gd.cc.s
.PHONY : vowpalwabbit/gd.s

# target to generate assembly for a file
vowpalwabbit/gd.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd.cc.s
.PHONY : vowpalwabbit/gd.cc.s

vowpalwabbit/gd_mf.o: vowpalwabbit/gd_mf.cc.o
.PHONY : vowpalwabbit/gd_mf.o

# target to build an object file
vowpalwabbit/gd_mf.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd_mf.cc.o
.PHONY : vowpalwabbit/gd_mf.cc.o

vowpalwabbit/gd_mf.i: vowpalwabbit/gd_mf.cc.i
.PHONY : vowpalwabbit/gd_mf.i

# target to preprocess a source file
vowpalwabbit/gd_mf.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd_mf.cc.i
.PHONY : vowpalwabbit/gd_mf.cc.i

vowpalwabbit/gd_mf.s: vowpalwabbit/gd_mf.cc.s
.PHONY : vowpalwabbit/gd_mf.s

# target to generate assembly for a file
vowpalwabbit/gd_mf.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gd_mf.cc.s
.PHONY : vowpalwabbit/gd_mf.cc.s

vowpalwabbit/gen_ns.o: vowpalwabbit/gen_ns.cc.o
.PHONY : vowpalwabbit/gen_ns.o

# target to build an object file
vowpalwabbit/gen_ns.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gen_ns.cc.o
.PHONY : vowpalwabbit/gen_ns.cc.o

vowpalwabbit/gen_ns.i: vowpalwabbit/gen_ns.cc.i
.PHONY : vowpalwabbit/gen_ns.i

# target to preprocess a source file
vowpalwabbit/gen_ns.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gen_ns.cc.i
.PHONY : vowpalwabbit/gen_ns.cc.i

vowpalwabbit/gen_ns.s: vowpalwabbit/gen_ns.cc.s
.PHONY : vowpalwabbit/gen_ns.s

# target to generate assembly for a file
vowpalwabbit/gen_ns.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/gen_ns.cc.s
.PHONY : vowpalwabbit/gen_ns.cc.s

vowpalwabbit/global_data.o: vowpalwabbit/global_data.cc.o
.PHONY : vowpalwabbit/global_data.o

# target to build an object file
vowpalwabbit/global_data.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/global_data.cc.o
.PHONY : vowpalwabbit/global_data.cc.o

vowpalwabbit/global_data.i: vowpalwabbit/global_data.cc.i
.PHONY : vowpalwabbit/global_data.i

# target to preprocess a source file
vowpalwabbit/global_data.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/global_data.cc.i
.PHONY : vowpalwabbit/global_data.cc.i

vowpalwabbit/global_data.s: vowpalwabbit/global_data.cc.s
.PHONY : vowpalwabbit/global_data.s

# target to generate assembly for a file
vowpalwabbit/global_data.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/global_data.cc.s
.PHONY : vowpalwabbit/global_data.cc.s

vowpalwabbit/hash.o: vowpalwabbit/hash.cc.o
.PHONY : vowpalwabbit/hash.o

# target to build an object file
vowpalwabbit/hash.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/hash.cc.o
.PHONY : vowpalwabbit/hash.cc.o

vowpalwabbit/hash.i: vowpalwabbit/hash.cc.i
.PHONY : vowpalwabbit/hash.i

# target to preprocess a source file
vowpalwabbit/hash.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/hash.cc.i
.PHONY : vowpalwabbit/hash.cc.i

vowpalwabbit/hash.s: vowpalwabbit/hash.cc.s
.PHONY : vowpalwabbit/hash.s

# target to generate assembly for a file
vowpalwabbit/hash.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/hash.cc.s
.PHONY : vowpalwabbit/hash.cc.s

vowpalwabbit/interact.o: vowpalwabbit/interact.cc.o
.PHONY : vowpalwabbit/interact.o

# target to build an object file
vowpalwabbit/interact.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interact.cc.o
.PHONY : vowpalwabbit/interact.cc.o

vowpalwabbit/interact.i: vowpalwabbit/interact.cc.i
.PHONY : vowpalwabbit/interact.i

# target to preprocess a source file
vowpalwabbit/interact.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interact.cc.i
.PHONY : vowpalwabbit/interact.cc.i

vowpalwabbit/interact.s: vowpalwabbit/interact.cc.s
.PHONY : vowpalwabbit/interact.s

# target to generate assembly for a file
vowpalwabbit/interact.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interact.cc.s
.PHONY : vowpalwabbit/interact.cc.s

vowpalwabbit/interactions.o: vowpalwabbit/interactions.cc.o
.PHONY : vowpalwabbit/interactions.o

# target to build an object file
vowpalwabbit/interactions.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interactions.cc.o
.PHONY : vowpalwabbit/interactions.cc.o

vowpalwabbit/interactions.i: vowpalwabbit/interactions.cc.i
.PHONY : vowpalwabbit/interactions.i

# target to preprocess a source file
vowpalwabbit/interactions.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interactions.cc.i
.PHONY : vowpalwabbit/interactions.cc.i

vowpalwabbit/interactions.s: vowpalwabbit/interactions.cc.s
.PHONY : vowpalwabbit/interactions.s

# target to generate assembly for a file
vowpalwabbit/interactions.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/interactions.cc.s
.PHONY : vowpalwabbit/interactions.cc.s

vowpalwabbit/io_buf.o: vowpalwabbit/io_buf.cc.o
.PHONY : vowpalwabbit/io_buf.o

# target to build an object file
vowpalwabbit/io_buf.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/io_buf.cc.o
.PHONY : vowpalwabbit/io_buf.cc.o

vowpalwabbit/io_buf.i: vowpalwabbit/io_buf.cc.i
.PHONY : vowpalwabbit/io_buf.i

# target to preprocess a source file
vowpalwabbit/io_buf.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/io_buf.cc.i
.PHONY : vowpalwabbit/io_buf.cc.i

vowpalwabbit/io_buf.s: vowpalwabbit/io_buf.cc.s
.PHONY : vowpalwabbit/io_buf.s

# target to generate assembly for a file
vowpalwabbit/io_buf.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/io_buf.cc.s
.PHONY : vowpalwabbit/io_buf.cc.s

vowpalwabbit/kernel_svm.o: vowpalwabbit/kernel_svm.cc.o
.PHONY : vowpalwabbit/kernel_svm.o

# target to build an object file
vowpalwabbit/kernel_svm.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/kernel_svm.cc.o
.PHONY : vowpalwabbit/kernel_svm.cc.o

vowpalwabbit/kernel_svm.i: vowpalwabbit/kernel_svm.cc.i
.PHONY : vowpalwabbit/kernel_svm.i

# target to preprocess a source file
vowpalwabbit/kernel_svm.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/kernel_svm.cc.i
.PHONY : vowpalwabbit/kernel_svm.cc.i

vowpalwabbit/kernel_svm.s: vowpalwabbit/kernel_svm.cc.s
.PHONY : vowpalwabbit/kernel_svm.s

# target to generate assembly for a file
vowpalwabbit/kernel_svm.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/kernel_svm.cc.s
.PHONY : vowpalwabbit/kernel_svm.cc.s

vowpalwabbit/label_dictionary.o: vowpalwabbit/label_dictionary.cc.o
.PHONY : vowpalwabbit/label_dictionary.o

# target to build an object file
vowpalwabbit/label_dictionary.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/label_dictionary.cc.o
.PHONY : vowpalwabbit/label_dictionary.cc.o

vowpalwabbit/label_dictionary.i: vowpalwabbit/label_dictionary.cc.i
.PHONY : vowpalwabbit/label_dictionary.i

# target to preprocess a source file
vowpalwabbit/label_dictionary.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/label_dictionary.cc.i
.PHONY : vowpalwabbit/label_dictionary.cc.i

vowpalwabbit/label_dictionary.s: vowpalwabbit/label_dictionary.cc.s
.PHONY : vowpalwabbit/label_dictionary.s

# target to generate assembly for a file
vowpalwabbit/label_dictionary.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/label_dictionary.cc.s
.PHONY : vowpalwabbit/label_dictionary.cc.s

vowpalwabbit/lda_core.o: vowpalwabbit/lda_core.cc.o
.PHONY : vowpalwabbit/lda_core.o

# target to build an object file
vowpalwabbit/lda_core.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lda_core.cc.o
.PHONY : vowpalwabbit/lda_core.cc.o

vowpalwabbit/lda_core.i: vowpalwabbit/lda_core.cc.i
.PHONY : vowpalwabbit/lda_core.i

# target to preprocess a source file
vowpalwabbit/lda_core.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lda_core.cc.i
.PHONY : vowpalwabbit/lda_core.cc.i

vowpalwabbit/lda_core.s: vowpalwabbit/lda_core.cc.s
.PHONY : vowpalwabbit/lda_core.s

# target to generate assembly for a file
vowpalwabbit/lda_core.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lda_core.cc.s
.PHONY : vowpalwabbit/lda_core.cc.s

vowpalwabbit/learner.o: vowpalwabbit/learner.cc.o
.PHONY : vowpalwabbit/learner.o

# target to build an object file
vowpalwabbit/learner.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/learner.cc.o
.PHONY : vowpalwabbit/learner.cc.o

vowpalwabbit/learner.i: vowpalwabbit/learner.cc.i
.PHONY : vowpalwabbit/learner.i

# target to preprocess a source file
vowpalwabbit/learner.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/learner.cc.i
.PHONY : vowpalwabbit/learner.cc.i

vowpalwabbit/learner.s: vowpalwabbit/learner.cc.s
.PHONY : vowpalwabbit/learner.s

# target to generate assembly for a file
vowpalwabbit/learner.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/learner.cc.s
.PHONY : vowpalwabbit/learner.cc.s

vowpalwabbit/log_multi.o: vowpalwabbit/log_multi.cc.o
.PHONY : vowpalwabbit/log_multi.o

# target to build an object file
vowpalwabbit/log_multi.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/log_multi.cc.o
.PHONY : vowpalwabbit/log_multi.cc.o

vowpalwabbit/log_multi.i: vowpalwabbit/log_multi.cc.i
.PHONY : vowpalwabbit/log_multi.i

# target to preprocess a source file
vowpalwabbit/log_multi.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/log_multi.cc.i
.PHONY : vowpalwabbit/log_multi.cc.i

vowpalwabbit/log_multi.s: vowpalwabbit/log_multi.cc.s
.PHONY : vowpalwabbit/log_multi.s

# target to generate assembly for a file
vowpalwabbit/log_multi.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/log_multi.cc.s
.PHONY : vowpalwabbit/log_multi.cc.s

vowpalwabbit/loss_functions.o: vowpalwabbit/loss_functions.cc.o
.PHONY : vowpalwabbit/loss_functions.o

# target to build an object file
vowpalwabbit/loss_functions.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/loss_functions.cc.o
.PHONY : vowpalwabbit/loss_functions.cc.o

vowpalwabbit/loss_functions.i: vowpalwabbit/loss_functions.cc.i
.PHONY : vowpalwabbit/loss_functions.i

# target to preprocess a source file
vowpalwabbit/loss_functions.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/loss_functions.cc.i
.PHONY : vowpalwabbit/loss_functions.cc.i

vowpalwabbit/loss_functions.s: vowpalwabbit/loss_functions.cc.s
.PHONY : vowpalwabbit/loss_functions.s

# target to generate assembly for a file
vowpalwabbit/loss_functions.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/loss_functions.cc.s
.PHONY : vowpalwabbit/loss_functions.cc.s

vowpalwabbit/lrq.o: vowpalwabbit/lrq.cc.o
.PHONY : vowpalwabbit/lrq.o

# target to build an object file
vowpalwabbit/lrq.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrq.cc.o
.PHONY : vowpalwabbit/lrq.cc.o

vowpalwabbit/lrq.i: vowpalwabbit/lrq.cc.i
.PHONY : vowpalwabbit/lrq.i

# target to preprocess a source file
vowpalwabbit/lrq.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrq.cc.i
.PHONY : vowpalwabbit/lrq.cc.i

vowpalwabbit/lrq.s: vowpalwabbit/lrq.cc.s
.PHONY : vowpalwabbit/lrq.s

# target to generate assembly for a file
vowpalwabbit/lrq.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrq.cc.s
.PHONY : vowpalwabbit/lrq.cc.s

vowpalwabbit/lrqfa.o: vowpalwabbit/lrqfa.cc.o
.PHONY : vowpalwabbit/lrqfa.o

# target to build an object file
vowpalwabbit/lrqfa.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrqfa.cc.o
.PHONY : vowpalwabbit/lrqfa.cc.o

vowpalwabbit/lrqfa.i: vowpalwabbit/lrqfa.cc.i
.PHONY : vowpalwabbit/lrqfa.i

# target to preprocess a source file
vowpalwabbit/lrqfa.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrqfa.cc.i
.PHONY : vowpalwabbit/lrqfa.cc.i

vowpalwabbit/lrqfa.s: vowpalwabbit/lrqfa.cc.s
.PHONY : vowpalwabbit/lrqfa.s

# target to generate assembly for a file
vowpalwabbit/lrqfa.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/lrqfa.cc.s
.PHONY : vowpalwabbit/lrqfa.cc.s

vowpalwabbit/main.o: vowpalwabbit/main.cc.o
.PHONY : vowpalwabbit/main.o

# target to build an object file
vowpalwabbit/main.cc.o:
	$(MAKE) -f CMakeFiles/vwexe.dir/build.make CMakeFiles/vwexe.dir/vowpalwabbit/main.cc.o
.PHONY : vowpalwabbit/main.cc.o

vowpalwabbit/main.i: vowpalwabbit/main.cc.i
.PHONY : vowpalwabbit/main.i

# target to preprocess a source file
vowpalwabbit/main.cc.i:
	$(MAKE) -f CMakeFiles/vwexe.dir/build.make CMakeFiles/vwexe.dir/vowpalwabbit/main.cc.i
.PHONY : vowpalwabbit/main.cc.i

vowpalwabbit/main.s: vowpalwabbit/main.cc.s
.PHONY : vowpalwabbit/main.s

# target to generate assembly for a file
vowpalwabbit/main.cc.s:
	$(MAKE) -f CMakeFiles/vwexe.dir/build.make CMakeFiles/vwexe.dir/vowpalwabbit/main.cc.s
.PHONY : vowpalwabbit/main.cc.s

vowpalwabbit/mf.o: vowpalwabbit/mf.cc.o
.PHONY : vowpalwabbit/mf.o

# target to build an object file
vowpalwabbit/mf.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/mf.cc.o
.PHONY : vowpalwabbit/mf.cc.o

vowpalwabbit/mf.i: vowpalwabbit/mf.cc.i
.PHONY : vowpalwabbit/mf.i

# target to preprocess a source file
vowpalwabbit/mf.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/mf.cc.i
.PHONY : vowpalwabbit/mf.cc.i

vowpalwabbit/mf.s: vowpalwabbit/mf.cc.s
.PHONY : vowpalwabbit/mf.s

# target to generate assembly for a file
vowpalwabbit/mf.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/mf.cc.s
.PHONY : vowpalwabbit/mf.cc.s

vowpalwabbit/multiclass.o: vowpalwabbit/multiclass.cc.o
.PHONY : vowpalwabbit/multiclass.o

# target to build an object file
vowpalwabbit/multiclass.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multiclass.cc.o
.PHONY : vowpalwabbit/multiclass.cc.o

vowpalwabbit/multiclass.i: vowpalwabbit/multiclass.cc.i
.PHONY : vowpalwabbit/multiclass.i

# target to preprocess a source file
vowpalwabbit/multiclass.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multiclass.cc.i
.PHONY : vowpalwabbit/multiclass.cc.i

vowpalwabbit/multiclass.s: vowpalwabbit/multiclass.cc.s
.PHONY : vowpalwabbit/multiclass.s

# target to generate assembly for a file
vowpalwabbit/multiclass.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multiclass.cc.s
.PHONY : vowpalwabbit/multiclass.cc.s

vowpalwabbit/multilabel.o: vowpalwabbit/multilabel.cc.o
.PHONY : vowpalwabbit/multilabel.o

# target to build an object file
vowpalwabbit/multilabel.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel.cc.o
.PHONY : vowpalwabbit/multilabel.cc.o

vowpalwabbit/multilabel.i: vowpalwabbit/multilabel.cc.i
.PHONY : vowpalwabbit/multilabel.i

# target to preprocess a source file
vowpalwabbit/multilabel.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel.cc.i
.PHONY : vowpalwabbit/multilabel.cc.i

vowpalwabbit/multilabel.s: vowpalwabbit/multilabel.cc.s
.PHONY : vowpalwabbit/multilabel.s

# target to generate assembly for a file
vowpalwabbit/multilabel.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel.cc.s
.PHONY : vowpalwabbit/multilabel.cc.s

vowpalwabbit/multilabel_oaa.o: vowpalwabbit/multilabel_oaa.cc.o
.PHONY : vowpalwabbit/multilabel_oaa.o

# target to build an object file
vowpalwabbit/multilabel_oaa.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel_oaa.cc.o
.PHONY : vowpalwabbit/multilabel_oaa.cc.o

vowpalwabbit/multilabel_oaa.i: vowpalwabbit/multilabel_oaa.cc.i
.PHONY : vowpalwabbit/multilabel_oaa.i

# target to preprocess a source file
vowpalwabbit/multilabel_oaa.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel_oaa.cc.i
.PHONY : vowpalwabbit/multilabel_oaa.cc.i

vowpalwabbit/multilabel_oaa.s: vowpalwabbit/multilabel_oaa.cc.s
.PHONY : vowpalwabbit/multilabel_oaa.s

# target to generate assembly for a file
vowpalwabbit/multilabel_oaa.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/multilabel_oaa.cc.s
.PHONY : vowpalwabbit/multilabel_oaa.cc.s

vowpalwabbit/network.o: vowpalwabbit/network.cc.o
.PHONY : vowpalwabbit/network.o

# target to build an object file
vowpalwabbit/network.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/network.cc.o
.PHONY : vowpalwabbit/network.cc.o

vowpalwabbit/network.i: vowpalwabbit/network.cc.i
.PHONY : vowpalwabbit/network.i

# target to preprocess a source file
vowpalwabbit/network.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/network.cc.i
.PHONY : vowpalwabbit/network.cc.i

vowpalwabbit/network.s: vowpalwabbit/network.cc.s
.PHONY : vowpalwabbit/network.s

# target to generate assembly for a file
vowpalwabbit/network.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/network.cc.s
.PHONY : vowpalwabbit/network.cc.s

vowpalwabbit/nn.o: vowpalwabbit/nn.cc.o
.PHONY : vowpalwabbit/nn.o

# target to build an object file
vowpalwabbit/nn.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/nn.cc.o
.PHONY : vowpalwabbit/nn.cc.o

vowpalwabbit/nn.i: vowpalwabbit/nn.cc.i
.PHONY : vowpalwabbit/nn.i

# target to preprocess a source file
vowpalwabbit/nn.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/nn.cc.i
.PHONY : vowpalwabbit/nn.cc.i

vowpalwabbit/nn.s: vowpalwabbit/nn.cc.s
.PHONY : vowpalwabbit/nn.s

# target to generate assembly for a file
vowpalwabbit/nn.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/nn.cc.s
.PHONY : vowpalwabbit/nn.cc.s

vowpalwabbit/noop.o: vowpalwabbit/noop.cc.o
.PHONY : vowpalwabbit/noop.o

# target to build an object file
vowpalwabbit/noop.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/noop.cc.o
.PHONY : vowpalwabbit/noop.cc.o

vowpalwabbit/noop.i: vowpalwabbit/noop.cc.i
.PHONY : vowpalwabbit/noop.i

# target to preprocess a source file
vowpalwabbit/noop.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/noop.cc.i
.PHONY : vowpalwabbit/noop.cc.i

vowpalwabbit/noop.s: vowpalwabbit/noop.cc.s
.PHONY : vowpalwabbit/noop.s

# target to generate assembly for a file
vowpalwabbit/noop.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/noop.cc.s
.PHONY : vowpalwabbit/noop.cc.s

vowpalwabbit/oaa.o: vowpalwabbit/oaa.cc.o
.PHONY : vowpalwabbit/oaa.o

# target to build an object file
vowpalwabbit/oaa.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/oaa.cc.o
.PHONY : vowpalwabbit/oaa.cc.o

vowpalwabbit/oaa.i: vowpalwabbit/oaa.cc.i
.PHONY : vowpalwabbit/oaa.i

# target to preprocess a source file
vowpalwabbit/oaa.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/oaa.cc.i
.PHONY : vowpalwabbit/oaa.cc.i

vowpalwabbit/oaa.s: vowpalwabbit/oaa.cc.s
.PHONY : vowpalwabbit/oaa.s

# target to generate assembly for a file
vowpalwabbit/oaa.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/oaa.cc.s
.PHONY : vowpalwabbit/oaa.cc.s

vowpalwabbit/parse_args.o: vowpalwabbit/parse_args.cc.o
.PHONY : vowpalwabbit/parse_args.o

# target to build an object file
vowpalwabbit/parse_args.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_args.cc.o
.PHONY : vowpalwabbit/parse_args.cc.o

vowpalwabbit/parse_args.i: vowpalwabbit/parse_args.cc.i
.PHONY : vowpalwabbit/parse_args.i

# target to preprocess a source file
vowpalwabbit/parse_args.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_args.cc.i
.PHONY : vowpalwabbit/parse_args.cc.i

vowpalwabbit/parse_args.s: vowpalwabbit/parse_args.cc.s
.PHONY : vowpalwabbit/parse_args.s

# target to generate assembly for a file
vowpalwabbit/parse_args.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_args.cc.s
.PHONY : vowpalwabbit/parse_args.cc.s

vowpalwabbit/parse_example.o: vowpalwabbit/parse_example.cc.o
.PHONY : vowpalwabbit/parse_example.o

# target to build an object file
vowpalwabbit/parse_example.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_example.cc.o
.PHONY : vowpalwabbit/parse_example.cc.o

vowpalwabbit/parse_example.i: vowpalwabbit/parse_example.cc.i
.PHONY : vowpalwabbit/parse_example.i

# target to preprocess a source file
vowpalwabbit/parse_example.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_example.cc.i
.PHONY : vowpalwabbit/parse_example.cc.i

vowpalwabbit/parse_example.s: vowpalwabbit/parse_example.cc.s
.PHONY : vowpalwabbit/parse_example.s

# target to generate assembly for a file
vowpalwabbit/parse_example.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_example.cc.s
.PHONY : vowpalwabbit/parse_example.cc.s

vowpalwabbit/parse_primitives.o: vowpalwabbit/parse_primitives.cc.o
.PHONY : vowpalwabbit/parse_primitives.o

# target to build an object file
vowpalwabbit/parse_primitives.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_primitives.cc.o
.PHONY : vowpalwabbit/parse_primitives.cc.o

vowpalwabbit/parse_primitives.i: vowpalwabbit/parse_primitives.cc.i
.PHONY : vowpalwabbit/parse_primitives.i

# target to preprocess a source file
vowpalwabbit/parse_primitives.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_primitives.cc.i
.PHONY : vowpalwabbit/parse_primitives.cc.i

vowpalwabbit/parse_primitives.s: vowpalwabbit/parse_primitives.cc.s
.PHONY : vowpalwabbit/parse_primitives.s

# target to generate assembly for a file
vowpalwabbit/parse_primitives.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_primitives.cc.s
.PHONY : vowpalwabbit/parse_primitives.cc.s

vowpalwabbit/parse_regressor.o: vowpalwabbit/parse_regressor.cc.o
.PHONY : vowpalwabbit/parse_regressor.o

# target to build an object file
vowpalwabbit/parse_regressor.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_regressor.cc.o
.PHONY : vowpalwabbit/parse_regressor.cc.o

vowpalwabbit/parse_regressor.i: vowpalwabbit/parse_regressor.cc.i
.PHONY : vowpalwabbit/parse_regressor.i

# target to preprocess a source file
vowpalwabbit/parse_regressor.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_regressor.cc.i
.PHONY : vowpalwabbit/parse_regressor.cc.i

vowpalwabbit/parse_regressor.s: vowpalwabbit/parse_regressor.cc.s
.PHONY : vowpalwabbit/parse_regressor.s

# target to generate assembly for a file
vowpalwabbit/parse_regressor.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_regressor.cc.s
.PHONY : vowpalwabbit/parse_regressor.cc.s

vowpalwabbit/parse_sframe.o: vowpalwabbit/parse_sframe.cc.o
.PHONY : vowpalwabbit/parse_sframe.o

# target to build an object file
vowpalwabbit/parse_sframe.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_sframe.cc.o
.PHONY : vowpalwabbit/parse_sframe.cc.o

vowpalwabbit/parse_sframe.i: vowpalwabbit/parse_sframe.cc.i
.PHONY : vowpalwabbit/parse_sframe.i

# target to preprocess a source file
vowpalwabbit/parse_sframe.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_sframe.cc.i
.PHONY : vowpalwabbit/parse_sframe.cc.i

vowpalwabbit/parse_sframe.s: vowpalwabbit/parse_sframe.cc.s
.PHONY : vowpalwabbit/parse_sframe.s

# target to generate assembly for a file
vowpalwabbit/parse_sframe.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parse_sframe.cc.s
.PHONY : vowpalwabbit/parse_sframe.cc.s

vowpalwabbit/parser.o: vowpalwabbit/parser.cc.o
.PHONY : vowpalwabbit/parser.o

# target to build an object file
vowpalwabbit/parser.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parser.cc.o
.PHONY : vowpalwabbit/parser.cc.o

vowpalwabbit/parser.i: vowpalwabbit/parser.cc.i
.PHONY : vowpalwabbit/parser.i

# target to preprocess a source file
vowpalwabbit/parser.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parser.cc.i
.PHONY : vowpalwabbit/parser.cc.i

vowpalwabbit/parser.s: vowpalwabbit/parser.cc.s
.PHONY : vowpalwabbit/parser.s

# target to generate assembly for a file
vowpalwabbit/parser.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/parser.cc.s
.PHONY : vowpalwabbit/parser.cc.s

vowpalwabbit/print.o: vowpalwabbit/print.cc.o
.PHONY : vowpalwabbit/print.o

# target to build an object file
vowpalwabbit/print.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/print.cc.o
.PHONY : vowpalwabbit/print.cc.o

vowpalwabbit/print.i: vowpalwabbit/print.cc.i
.PHONY : vowpalwabbit/print.i

# target to preprocess a source file
vowpalwabbit/print.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/print.cc.i
.PHONY : vowpalwabbit/print.cc.i

vowpalwabbit/print.s: vowpalwabbit/print.cc.s
.PHONY : vowpalwabbit/print.s

# target to generate assembly for a file
vowpalwabbit/print.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/print.cc.s
.PHONY : vowpalwabbit/print.cc.s

vowpalwabbit/rand48.o: vowpalwabbit/rand48.cc.o
.PHONY : vowpalwabbit/rand48.o

# target to build an object file
vowpalwabbit/rand48.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/rand48.cc.o
.PHONY : vowpalwabbit/rand48.cc.o

vowpalwabbit/rand48.i: vowpalwabbit/rand48.cc.i
.PHONY : vowpalwabbit/rand48.i

# target to preprocess a source file
vowpalwabbit/rand48.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/rand48.cc.i
.PHONY : vowpalwabbit/rand48.cc.i

vowpalwabbit/rand48.s: vowpalwabbit/rand48.cc.s
.PHONY : vowpalwabbit/rand48.s

# target to generate assembly for a file
vowpalwabbit/rand48.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/rand48.cc.s
.PHONY : vowpalwabbit/rand48.cc.s

vowpalwabbit/scorer.o: vowpalwabbit/scorer.cc.o
.PHONY : vowpalwabbit/scorer.o

# target to build an object file
vowpalwabbit/scorer.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/scorer.cc.o
.PHONY : vowpalwabbit/scorer.cc.o

vowpalwabbit/scorer.i: vowpalwabbit/scorer.cc.i
.PHONY : vowpalwabbit/scorer.i

# target to preprocess a source file
vowpalwabbit/scorer.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/scorer.cc.i
.PHONY : vowpalwabbit/scorer.cc.i

vowpalwabbit/scorer.s: vowpalwabbit/scorer.cc.s
.PHONY : vowpalwabbit/scorer.s

# target to generate assembly for a file
vowpalwabbit/scorer.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/scorer.cc.s
.PHONY : vowpalwabbit/scorer.cc.s

vowpalwabbit/search.o: vowpalwabbit/search.cc.o
.PHONY : vowpalwabbit/search.o

# target to build an object file
vowpalwabbit/search.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search.cc.o
.PHONY : vowpalwabbit/search.cc.o

vowpalwabbit/search.i: vowpalwabbit/search.cc.i
.PHONY : vowpalwabbit/search.i

# target to preprocess a source file
vowpalwabbit/search.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search.cc.i
.PHONY : vowpalwabbit/search.cc.i

vowpalwabbit/search.s: vowpalwabbit/search.cc.s
.PHONY : vowpalwabbit/search.s

# target to generate assembly for a file
vowpalwabbit/search.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search.cc.s
.PHONY : vowpalwabbit/search.cc.s

vowpalwabbit/search_dep_parser.o: vowpalwabbit/search_dep_parser.cc.o
.PHONY : vowpalwabbit/search_dep_parser.o

# target to build an object file
vowpalwabbit/search_dep_parser.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_dep_parser.cc.o
.PHONY : vowpalwabbit/search_dep_parser.cc.o

vowpalwabbit/search_dep_parser.i: vowpalwabbit/search_dep_parser.cc.i
.PHONY : vowpalwabbit/search_dep_parser.i

# target to preprocess a source file
vowpalwabbit/search_dep_parser.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_dep_parser.cc.i
.PHONY : vowpalwabbit/search_dep_parser.cc.i

vowpalwabbit/search_dep_parser.s: vowpalwabbit/search_dep_parser.cc.s
.PHONY : vowpalwabbit/search_dep_parser.s

# target to generate assembly for a file
vowpalwabbit/search_dep_parser.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_dep_parser.cc.s
.PHONY : vowpalwabbit/search_dep_parser.cc.s

vowpalwabbit/search_entityrelationtask.o: vowpalwabbit/search_entityrelationtask.cc.o
.PHONY : vowpalwabbit/search_entityrelationtask.o

# target to build an object file
vowpalwabbit/search_entityrelationtask.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_entityrelationtask.cc.o
.PHONY : vowpalwabbit/search_entityrelationtask.cc.o

vowpalwabbit/search_entityrelationtask.i: vowpalwabbit/search_entityrelationtask.cc.i
.PHONY : vowpalwabbit/search_entityrelationtask.i

# target to preprocess a source file
vowpalwabbit/search_entityrelationtask.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_entityrelationtask.cc.i
.PHONY : vowpalwabbit/search_entityrelationtask.cc.i

vowpalwabbit/search_entityrelationtask.s: vowpalwabbit/search_entityrelationtask.cc.s
.PHONY : vowpalwabbit/search_entityrelationtask.s

# target to generate assembly for a file
vowpalwabbit/search_entityrelationtask.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_entityrelationtask.cc.s
.PHONY : vowpalwabbit/search_entityrelationtask.cc.s

vowpalwabbit/search_graph.o: vowpalwabbit/search_graph.cc.o
.PHONY : vowpalwabbit/search_graph.o

# target to build an object file
vowpalwabbit/search_graph.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_graph.cc.o
.PHONY : vowpalwabbit/search_graph.cc.o

vowpalwabbit/search_graph.i: vowpalwabbit/search_graph.cc.i
.PHONY : vowpalwabbit/search_graph.i

# target to preprocess a source file
vowpalwabbit/search_graph.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_graph.cc.i
.PHONY : vowpalwabbit/search_graph.cc.i

vowpalwabbit/search_graph.s: vowpalwabbit/search_graph.cc.s
.PHONY : vowpalwabbit/search_graph.s

# target to generate assembly for a file
vowpalwabbit/search_graph.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_graph.cc.s
.PHONY : vowpalwabbit/search_graph.cc.s

vowpalwabbit/search_hooktask.o: vowpalwabbit/search_hooktask.cc.o
.PHONY : vowpalwabbit/search_hooktask.o

# target to build an object file
vowpalwabbit/search_hooktask.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_hooktask.cc.o
.PHONY : vowpalwabbit/search_hooktask.cc.o

vowpalwabbit/search_hooktask.i: vowpalwabbit/search_hooktask.cc.i
.PHONY : vowpalwabbit/search_hooktask.i

# target to preprocess a source file
vowpalwabbit/search_hooktask.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_hooktask.cc.i
.PHONY : vowpalwabbit/search_hooktask.cc.i

vowpalwabbit/search_hooktask.s: vowpalwabbit/search_hooktask.cc.s
.PHONY : vowpalwabbit/search_hooktask.s

# target to generate assembly for a file
vowpalwabbit/search_hooktask.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_hooktask.cc.s
.PHONY : vowpalwabbit/search_hooktask.cc.s

vowpalwabbit/search_meta.o: vowpalwabbit/search_meta.cc.o
.PHONY : vowpalwabbit/search_meta.o

# target to build an object file
vowpalwabbit/search_meta.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_meta.cc.o
.PHONY : vowpalwabbit/search_meta.cc.o

vowpalwabbit/search_meta.i: vowpalwabbit/search_meta.cc.i
.PHONY : vowpalwabbit/search_meta.i

# target to preprocess a source file
vowpalwabbit/search_meta.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_meta.cc.i
.PHONY : vowpalwabbit/search_meta.cc.i

vowpalwabbit/search_meta.s: vowpalwabbit/search_meta.cc.s
.PHONY : vowpalwabbit/search_meta.s

# target to generate assembly for a file
vowpalwabbit/search_meta.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_meta.cc.s
.PHONY : vowpalwabbit/search_meta.cc.s

vowpalwabbit/search_multiclasstask.o: vowpalwabbit/search_multiclasstask.cc.o
.PHONY : vowpalwabbit/search_multiclasstask.o

# target to build an object file
vowpalwabbit/search_multiclasstask.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_multiclasstask.cc.o
.PHONY : vowpalwabbit/search_multiclasstask.cc.o

vowpalwabbit/search_multiclasstask.i: vowpalwabbit/search_multiclasstask.cc.i
.PHONY : vowpalwabbit/search_multiclasstask.i

# target to preprocess a source file
vowpalwabbit/search_multiclasstask.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_multiclasstask.cc.i
.PHONY : vowpalwabbit/search_multiclasstask.cc.i

vowpalwabbit/search_multiclasstask.s: vowpalwabbit/search_multiclasstask.cc.s
.PHONY : vowpalwabbit/search_multiclasstask.s

# target to generate assembly for a file
vowpalwabbit/search_multiclasstask.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_multiclasstask.cc.s
.PHONY : vowpalwabbit/search_multiclasstask.cc.s

vowpalwabbit/search_sequencetask.o: vowpalwabbit/search_sequencetask.cc.o
.PHONY : vowpalwabbit/search_sequencetask.o

# target to build an object file
vowpalwabbit/search_sequencetask.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_sequencetask.cc.o
.PHONY : vowpalwabbit/search_sequencetask.cc.o

vowpalwabbit/search_sequencetask.i: vowpalwabbit/search_sequencetask.cc.i
.PHONY : vowpalwabbit/search_sequencetask.i

# target to preprocess a source file
vowpalwabbit/search_sequencetask.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_sequencetask.cc.i
.PHONY : vowpalwabbit/search_sequencetask.cc.i

vowpalwabbit/search_sequencetask.s: vowpalwabbit/search_sequencetask.cc.s
.PHONY : vowpalwabbit/search_sequencetask.s

# target to generate assembly for a file
vowpalwabbit/search_sequencetask.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/search_sequencetask.cc.s
.PHONY : vowpalwabbit/search_sequencetask.cc.s

vowpalwabbit/sender.o: vowpalwabbit/sender.cc.o
.PHONY : vowpalwabbit/sender.o

# target to build an object file
vowpalwabbit/sender.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/sender.cc.o
.PHONY : vowpalwabbit/sender.cc.o

vowpalwabbit/sender.i: vowpalwabbit/sender.cc.i
.PHONY : vowpalwabbit/sender.i

# target to preprocess a source file
vowpalwabbit/sender.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/sender.cc.i
.PHONY : vowpalwabbit/sender.cc.i

vowpalwabbit/sender.s: vowpalwabbit/sender.cc.s
.PHONY : vowpalwabbit/sender.s

# target to generate assembly for a file
vowpalwabbit/sender.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/sender.cc.s
.PHONY : vowpalwabbit/sender.cc.s

vowpalwabbit/simple_label.o: vowpalwabbit/simple_label.cc.o
.PHONY : vowpalwabbit/simple_label.o

# target to build an object file
vowpalwabbit/simple_label.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/simple_label.cc.o
.PHONY : vowpalwabbit/simple_label.cc.o

vowpalwabbit/simple_label.i: vowpalwabbit/simple_label.cc.i
.PHONY : vowpalwabbit/simple_label.i

# target to preprocess a source file
vowpalwabbit/simple_label.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/simple_label.cc.i
.PHONY : vowpalwabbit/simple_label.cc.i

vowpalwabbit/simple_label.s: vowpalwabbit/simple_label.cc.s
.PHONY : vowpalwabbit/simple_label.s

# target to generate assembly for a file
vowpalwabbit/simple_label.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/simple_label.cc.s
.PHONY : vowpalwabbit/simple_label.cc.s

vowpalwabbit/spanning_tree.o: vowpalwabbit/spanning_tree.cc.o
.PHONY : vowpalwabbit/spanning_tree.o

# target to build an object file
vowpalwabbit/spanning_tree.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/spanning_tree.cc.o
.PHONY : vowpalwabbit/spanning_tree.cc.o

vowpalwabbit/spanning_tree.i: vowpalwabbit/spanning_tree.cc.i
.PHONY : vowpalwabbit/spanning_tree.i

# target to preprocess a source file
vowpalwabbit/spanning_tree.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/spanning_tree.cc.i
.PHONY : vowpalwabbit/spanning_tree.cc.i

vowpalwabbit/spanning_tree.s: vowpalwabbit/spanning_tree.cc.s
.PHONY : vowpalwabbit/spanning_tree.s

# target to generate assembly for a file
vowpalwabbit/spanning_tree.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/spanning_tree.cc.s
.PHONY : vowpalwabbit/spanning_tree.cc.s

vowpalwabbit/stagewise_poly.o: vowpalwabbit/stagewise_poly.cc.o
.PHONY : vowpalwabbit/stagewise_poly.o

# target to build an object file
vowpalwabbit/stagewise_poly.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/stagewise_poly.cc.o
.PHONY : vowpalwabbit/stagewise_poly.cc.o

vowpalwabbit/stagewise_poly.i: vowpalwabbit/stagewise_poly.cc.i
.PHONY : vowpalwabbit/stagewise_poly.i

# target to preprocess a source file
vowpalwabbit/stagewise_poly.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/stagewise_poly.cc.i
.PHONY : vowpalwabbit/stagewise_poly.cc.i

vowpalwabbit/stagewise_poly.s: vowpalwabbit/stagewise_poly.cc.s
.PHONY : vowpalwabbit/stagewise_poly.s

# target to generate assembly for a file
vowpalwabbit/stagewise_poly.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/stagewise_poly.cc.s
.PHONY : vowpalwabbit/stagewise_poly.cc.s

vowpalwabbit/svrg.o: vowpalwabbit/svrg.cc.o
.PHONY : vowpalwabbit/svrg.o

# target to build an object file
vowpalwabbit/svrg.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/svrg.cc.o
.PHONY : vowpalwabbit/svrg.cc.o

vowpalwabbit/svrg.i: vowpalwabbit/svrg.cc.i
.PHONY : vowpalwabbit/svrg.i

# target to preprocess a source file
vowpalwabbit/svrg.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/svrg.cc.i
.PHONY : vowpalwabbit/svrg.cc.i

vowpalwabbit/svrg.s: vowpalwabbit/svrg.cc.s
.PHONY : vowpalwabbit/svrg.s

# target to generate assembly for a file
vowpalwabbit/svrg.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/svrg.cc.s
.PHONY : vowpalwabbit/svrg.cc.s

vowpalwabbit/topk.o: vowpalwabbit/topk.cc.o
.PHONY : vowpalwabbit/topk.o

# target to build an object file
vowpalwabbit/topk.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/topk.cc.o
.PHONY : vowpalwabbit/topk.cc.o

vowpalwabbit/topk.i: vowpalwabbit/topk.cc.i
.PHONY : vowpalwabbit/topk.i

# target to preprocess a source file
vowpalwabbit/topk.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/topk.cc.i
.PHONY : vowpalwabbit/topk.cc.i

vowpalwabbit/topk.s: vowpalwabbit/topk.cc.s
.PHONY : vowpalwabbit/topk.s

# target to generate assembly for a file
vowpalwabbit/topk.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/topk.cc.s
.PHONY : vowpalwabbit/topk.cc.s

vowpalwabbit/unique_sort.o: vowpalwabbit/unique_sort.cc.o
.PHONY : vowpalwabbit/unique_sort.o

# target to build an object file
vowpalwabbit/unique_sort.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/unique_sort.cc.o
.PHONY : vowpalwabbit/unique_sort.cc.o

vowpalwabbit/unique_sort.i: vowpalwabbit/unique_sort.cc.i
.PHONY : vowpalwabbit/unique_sort.i

# target to preprocess a source file
vowpalwabbit/unique_sort.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/unique_sort.cc.i
.PHONY : vowpalwabbit/unique_sort.cc.i

vowpalwabbit/unique_sort.s: vowpalwabbit/unique_sort.cc.s
.PHONY : vowpalwabbit/unique_sort.s

# target to generate assembly for a file
vowpalwabbit/unique_sort.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/unique_sort.cc.s
.PHONY : vowpalwabbit/unique_sort.cc.s

vowpalwabbit/vw_exception.o: vowpalwabbit/vw_exception.cc.o
.PHONY : vowpalwabbit/vw_exception.o

# target to build an object file
vowpalwabbit/vw_exception.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_exception.cc.o
.PHONY : vowpalwabbit/vw_exception.cc.o

vowpalwabbit/vw_exception.i: vowpalwabbit/vw_exception.cc.i
.PHONY : vowpalwabbit/vw_exception.i

# target to preprocess a source file
vowpalwabbit/vw_exception.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_exception.cc.i
.PHONY : vowpalwabbit/vw_exception.cc.i

vowpalwabbit/vw_exception.s: vowpalwabbit/vw_exception.cc.s
.PHONY : vowpalwabbit/vw_exception.s

# target to generate assembly for a file
vowpalwabbit/vw_exception.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_exception.cc.s
.PHONY : vowpalwabbit/vw_exception.cc.s

vowpalwabbit/vw_validate.o: vowpalwabbit/vw_validate.cc.o
.PHONY : vowpalwabbit/vw_validate.o

# target to build an object file
vowpalwabbit/vw_validate.cc.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_validate.cc.o
.PHONY : vowpalwabbit/vw_validate.cc.o

vowpalwabbit/vw_validate.i: vowpalwabbit/vw_validate.cc.i
.PHONY : vowpalwabbit/vw_validate.i

# target to preprocess a source file
vowpalwabbit/vw_validate.cc.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_validate.cc.i
.PHONY : vowpalwabbit/vw_validate.cc.i

vowpalwabbit/vw_validate.s: vowpalwabbit/vw_validate.cc.s
.PHONY : vowpalwabbit/vw_validate.s

# target to generate assembly for a file
vowpalwabbit/vw_validate.cc.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vw_validate.cc.s
.PHONY : vowpalwabbit/vw_validate.cc.s

vowpalwabbit/vwdll.o: vowpalwabbit/vwdll.cpp.o
.PHONY : vowpalwabbit/vwdll.o

# target to build an object file
vowpalwabbit/vwdll.cpp.o:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vwdll.cpp.o
.PHONY : vowpalwabbit/vwdll.cpp.o

vowpalwabbit/vwdll.i: vowpalwabbit/vwdll.cpp.i
.PHONY : vowpalwabbit/vwdll.i

# target to preprocess a source file
vowpalwabbit/vwdll.cpp.i:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vwdll.cpp.i
.PHONY : vowpalwabbit/vwdll.cpp.i

vowpalwabbit/vwdll.s: vowpalwabbit/vwdll.cpp.s
.PHONY : vowpalwabbit/vwdll.s

# target to generate assembly for a file
vowpalwabbit/vwdll.cpp.s:
	$(MAKE) -f CMakeFiles/vw.dir/build.make CMakeFiles/vw.dir/vowpalwabbit/vwdll.cpp.s
.PHONY : vowpalwabbit/vwdll.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vw"
	@echo "... vwexe"
	@echo "... vowpalwabbit/accumulate.o"
	@echo "... vowpalwabbit/accumulate.i"
	@echo "... vowpalwabbit/accumulate.s"
	@echo "... vowpalwabbit/active.o"
	@echo "... vowpalwabbit/active.i"
	@echo "... vowpalwabbit/active.s"
	@echo "... vowpalwabbit/active_cover.o"
	@echo "... vowpalwabbit/active_cover.i"
	@echo "... vowpalwabbit/active_cover.s"
	@echo "... vowpalwabbit/allreduce_sockets.o"
	@echo "... vowpalwabbit/allreduce_sockets.i"
	@echo "... vowpalwabbit/allreduce_sockets.s"
	@echo "... vowpalwabbit/allreduce_threads.o"
	@echo "... vowpalwabbit/allreduce_threads.i"
	@echo "... vowpalwabbit/allreduce_threads.s"
	@echo "... vowpalwabbit/autolink.o"
	@echo "... vowpalwabbit/autolink.i"
	@echo "... vowpalwabbit/autolink.s"
	@echo "... vowpalwabbit/best_constant.o"
	@echo "... vowpalwabbit/best_constant.i"
	@echo "... vowpalwabbit/best_constant.s"
	@echo "... vowpalwabbit/bfgs.o"
	@echo "... vowpalwabbit/bfgs.i"
	@echo "... vowpalwabbit/bfgs.s"
	@echo "... vowpalwabbit/binary.o"
	@echo "... vowpalwabbit/binary.i"
	@echo "... vowpalwabbit/binary.s"
	@echo "... vowpalwabbit/boosting.o"
	@echo "... vowpalwabbit/boosting.i"
	@echo "... vowpalwabbit/boosting.s"
	@echo "... vowpalwabbit/bs.o"
	@echo "... vowpalwabbit/bs.i"
	@echo "... vowpalwabbit/bs.s"
	@echo "... vowpalwabbit/cache.o"
	@echo "... vowpalwabbit/cache.i"
	@echo "... vowpalwabbit/cache.s"
	@echo "... vowpalwabbit/cb.o"
	@echo "... vowpalwabbit/cb.i"
	@echo "... vowpalwabbit/cb.s"
	@echo "... vowpalwabbit/cb_adf.o"
	@echo "... vowpalwabbit/cb_adf.i"
	@echo "... vowpalwabbit/cb_adf.s"
	@echo "... vowpalwabbit/cb_algs.o"
	@echo "... vowpalwabbit/cb_algs.i"
	@echo "... vowpalwabbit/cb_algs.s"
	@echo "... vowpalwabbit/cbify.o"
	@echo "... vowpalwabbit/cbify.i"
	@echo "... vowpalwabbit/cbify.s"
	@echo "... vowpalwabbit/comp_io.o"
	@echo "... vowpalwabbit/comp_io.i"
	@echo "... vowpalwabbit/comp_io.s"
	@echo "... vowpalwabbit/cost_sensitive.o"
	@echo "... vowpalwabbit/cost_sensitive.i"
	@echo "... vowpalwabbit/cost_sensitive.s"
	@echo "... vowpalwabbit/csoaa.o"
	@echo "... vowpalwabbit/csoaa.i"
	@echo "... vowpalwabbit/csoaa.s"
	@echo "... vowpalwabbit/ect.o"
	@echo "... vowpalwabbit/ect.i"
	@echo "... vowpalwabbit/ect.s"
	@echo "... vowpalwabbit/example.o"
	@echo "... vowpalwabbit/example.i"
	@echo "... vowpalwabbit/example.s"
	@echo "... vowpalwabbit/ftrl.o"
	@echo "... vowpalwabbit/ftrl.i"
	@echo "... vowpalwabbit/ftrl.s"
	@echo "... vowpalwabbit/gd.o"
	@echo "... vowpalwabbit/gd.i"
	@echo "... vowpalwabbit/gd.s"
	@echo "... vowpalwabbit/gd_mf.o"
	@echo "... vowpalwabbit/gd_mf.i"
	@echo "... vowpalwabbit/gd_mf.s"
	@echo "... vowpalwabbit/gen_ns.o"
	@echo "... vowpalwabbit/gen_ns.i"
	@echo "... vowpalwabbit/gen_ns.s"
	@echo "... vowpalwabbit/global_data.o"
	@echo "... vowpalwabbit/global_data.i"
	@echo "... vowpalwabbit/global_data.s"
	@echo "... vowpalwabbit/hash.o"
	@echo "... vowpalwabbit/hash.i"
	@echo "... vowpalwabbit/hash.s"
	@echo "... vowpalwabbit/interact.o"
	@echo "... vowpalwabbit/interact.i"
	@echo "... vowpalwabbit/interact.s"
	@echo "... vowpalwabbit/interactions.o"
	@echo "... vowpalwabbit/interactions.i"
	@echo "... vowpalwabbit/interactions.s"
	@echo "... vowpalwabbit/io_buf.o"
	@echo "... vowpalwabbit/io_buf.i"
	@echo "... vowpalwabbit/io_buf.s"
	@echo "... vowpalwabbit/kernel_svm.o"
	@echo "... vowpalwabbit/kernel_svm.i"
	@echo "... vowpalwabbit/kernel_svm.s"
	@echo "... vowpalwabbit/label_dictionary.o"
	@echo "... vowpalwabbit/label_dictionary.i"
	@echo "... vowpalwabbit/label_dictionary.s"
	@echo "... vowpalwabbit/lda_core.o"
	@echo "... vowpalwabbit/lda_core.i"
	@echo "... vowpalwabbit/lda_core.s"
	@echo "... vowpalwabbit/learner.o"
	@echo "... vowpalwabbit/learner.i"
	@echo "... vowpalwabbit/learner.s"
	@echo "... vowpalwabbit/log_multi.o"
	@echo "... vowpalwabbit/log_multi.i"
	@echo "... vowpalwabbit/log_multi.s"
	@echo "... vowpalwabbit/loss_functions.o"
	@echo "... vowpalwabbit/loss_functions.i"
	@echo "... vowpalwabbit/loss_functions.s"
	@echo "... vowpalwabbit/lrq.o"
	@echo "... vowpalwabbit/lrq.i"
	@echo "... vowpalwabbit/lrq.s"
	@echo "... vowpalwabbit/lrqfa.o"
	@echo "... vowpalwabbit/lrqfa.i"
	@echo "... vowpalwabbit/lrqfa.s"
	@echo "... vowpalwabbit/main.o"
	@echo "... vowpalwabbit/main.i"
	@echo "... vowpalwabbit/main.s"
	@echo "... vowpalwabbit/mf.o"
	@echo "... vowpalwabbit/mf.i"
	@echo "... vowpalwabbit/mf.s"
	@echo "... vowpalwabbit/multiclass.o"
	@echo "... vowpalwabbit/multiclass.i"
	@echo "... vowpalwabbit/multiclass.s"
	@echo "... vowpalwabbit/multilabel.o"
	@echo "... vowpalwabbit/multilabel.i"
	@echo "... vowpalwabbit/multilabel.s"
	@echo "... vowpalwabbit/multilabel_oaa.o"
	@echo "... vowpalwabbit/multilabel_oaa.i"
	@echo "... vowpalwabbit/multilabel_oaa.s"
	@echo "... vowpalwabbit/network.o"
	@echo "... vowpalwabbit/network.i"
	@echo "... vowpalwabbit/network.s"
	@echo "... vowpalwabbit/nn.o"
	@echo "... vowpalwabbit/nn.i"
	@echo "... vowpalwabbit/nn.s"
	@echo "... vowpalwabbit/noop.o"
	@echo "... vowpalwabbit/noop.i"
	@echo "... vowpalwabbit/noop.s"
	@echo "... vowpalwabbit/oaa.o"
	@echo "... vowpalwabbit/oaa.i"
	@echo "... vowpalwabbit/oaa.s"
	@echo "... vowpalwabbit/parse_args.o"
	@echo "... vowpalwabbit/parse_args.i"
	@echo "... vowpalwabbit/parse_args.s"
	@echo "... vowpalwabbit/parse_example.o"
	@echo "... vowpalwabbit/parse_example.i"
	@echo "... vowpalwabbit/parse_example.s"
	@echo "... vowpalwabbit/parse_primitives.o"
	@echo "... vowpalwabbit/parse_primitives.i"
	@echo "... vowpalwabbit/parse_primitives.s"
	@echo "... vowpalwabbit/parse_regressor.o"
	@echo "... vowpalwabbit/parse_regressor.i"
	@echo "... vowpalwabbit/parse_regressor.s"
	@echo "... vowpalwabbit/parse_sframe.o"
	@echo "... vowpalwabbit/parse_sframe.i"
	@echo "... vowpalwabbit/parse_sframe.s"
	@echo "... vowpalwabbit/parser.o"
	@echo "... vowpalwabbit/parser.i"
	@echo "... vowpalwabbit/parser.s"
	@echo "... vowpalwabbit/print.o"
	@echo "... vowpalwabbit/print.i"
	@echo "... vowpalwabbit/print.s"
	@echo "... vowpalwabbit/rand48.o"
	@echo "... vowpalwabbit/rand48.i"
	@echo "... vowpalwabbit/rand48.s"
	@echo "... vowpalwabbit/scorer.o"
	@echo "... vowpalwabbit/scorer.i"
	@echo "... vowpalwabbit/scorer.s"
	@echo "... vowpalwabbit/search.o"
	@echo "... vowpalwabbit/search.i"
	@echo "... vowpalwabbit/search.s"
	@echo "... vowpalwabbit/search_dep_parser.o"
	@echo "... vowpalwabbit/search_dep_parser.i"
	@echo "... vowpalwabbit/search_dep_parser.s"
	@echo "... vowpalwabbit/search_entityrelationtask.o"
	@echo "... vowpalwabbit/search_entityrelationtask.i"
	@echo "... vowpalwabbit/search_entityrelationtask.s"
	@echo "... vowpalwabbit/search_graph.o"
	@echo "... vowpalwabbit/search_graph.i"
	@echo "... vowpalwabbit/search_graph.s"
	@echo "... vowpalwabbit/search_hooktask.o"
	@echo "... vowpalwabbit/search_hooktask.i"
	@echo "... vowpalwabbit/search_hooktask.s"
	@echo "... vowpalwabbit/search_meta.o"
	@echo "... vowpalwabbit/search_meta.i"
	@echo "... vowpalwabbit/search_meta.s"
	@echo "... vowpalwabbit/search_multiclasstask.o"
	@echo "... vowpalwabbit/search_multiclasstask.i"
	@echo "... vowpalwabbit/search_multiclasstask.s"
	@echo "... vowpalwabbit/search_sequencetask.o"
	@echo "... vowpalwabbit/search_sequencetask.i"
	@echo "... vowpalwabbit/search_sequencetask.s"
	@echo "... vowpalwabbit/sender.o"
	@echo "... vowpalwabbit/sender.i"
	@echo "... vowpalwabbit/sender.s"
	@echo "... vowpalwabbit/simple_label.o"
	@echo "... vowpalwabbit/simple_label.i"
	@echo "... vowpalwabbit/simple_label.s"
	@echo "... vowpalwabbit/spanning_tree.o"
	@echo "... vowpalwabbit/spanning_tree.i"
	@echo "... vowpalwabbit/spanning_tree.s"
	@echo "... vowpalwabbit/stagewise_poly.o"
	@echo "... vowpalwabbit/stagewise_poly.i"
	@echo "... vowpalwabbit/stagewise_poly.s"
	@echo "... vowpalwabbit/svrg.o"
	@echo "... vowpalwabbit/svrg.i"
	@echo "... vowpalwabbit/svrg.s"
	@echo "... vowpalwabbit/topk.o"
	@echo "... vowpalwabbit/topk.i"
	@echo "... vowpalwabbit/topk.s"
	@echo "... vowpalwabbit/unique_sort.o"
	@echo "... vowpalwabbit/unique_sort.i"
	@echo "... vowpalwabbit/unique_sort.s"
	@echo "... vowpalwabbit/vw_exception.o"
	@echo "... vowpalwabbit/vw_exception.i"
	@echo "... vowpalwabbit/vw_exception.s"
	@echo "... vowpalwabbit/vw_validate.o"
	@echo "... vowpalwabbit/vw_validate.i"
	@echo "... vowpalwabbit/vw_validate.s"
	@echo "... vowpalwabbit/vwdll.o"
	@echo "... vowpalwabbit/vwdll.i"
	@echo "... vowpalwabbit/vwdll.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

